name: Creating test env

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "Project name for duplicating"
        required: true

jobs:
  updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Login
        run: npx appwrite-cli-beta@0.16.87-e88c3240b2cb8d9ae6453bf09d4ecdcd82bd95 login --email "${{ secrets.EMAIL }}" --password "${{ secrets.PASSWORD }}"
      - name: Pull all resources
        run: npx appwrite-cli-beta@0.16.87-e88c3240b2cb8d9ae6453bf09d4ecdcd82bd95 pull all --all --force
      - name: Create a new project
        run: |
          id="$(date +%N)-${{ github.event.inputs.project_name }}"
          npx appwrite-cli-beta@0.16.87-e88c3240b2cb8d9ae6453bf09d4ecdcd82bd95 projects create --projectId "$id" --name "${{ github.event.inputs.project_name }}" --teamId "${{ secrets.ORGANIZATION }}"
          sed -E -i 's#"projectId": "(\S+)"#"projectId": "$id"#' appwrite.json
          sed -E -i 's#"projectName": "(\S+)"#"projectName": "${{ github.event.inputs.project_name }}"#' appwrite.json
      - name: Push all resources
        run: npx appwrite-cli-beta@0.16.87-e88c3240b2cb8d9ae6453bf09d4ecdcd82bd95 push all --all --force
