name: Migrating databases

on:
  release:
    types: [published]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Login
        run: npx appwrite-cli-beta@0.16.87-e88c3240b2cb8d9ae6453bf09d4ecdcd82bd95 login --email ${{ secrets.EMAIL }} --password ${{ secrets.PASSWORD }}
      - name: Migrate collections
        run: npx appwrite-cli-beta@0.16.87-e88c3240b2cb8d9ae6453bf09d4ecdcd82bd95 push collections --all --force
